# Generated by Django 5.2.8 on 2025-11-21 21:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('income_from_main_job', 'درامد از شغل اصلی'), ('income', 'درآمد'), ('important_expense', 'هزینه ضروری'), ('Additional costs', 'هزینه های جانبی'), ('savings', 'پس\u200cانداز/سرمایه\u200cگذاری')], default='expense', max_length=20)),
                ('color', models.CharField(choices=[('سبز', '#00A878'), ('آبی', '#2C73D2'), ('قرمز', '#E94F64'), ('نارنجی', '#FF7B29'), ('بنفش', '#8E7DBE'), ('خاکستری', '#AAB8C2')], default='Gray', max_length=100)),
                ('default_amount', models.PositiveIntegerField(blank=True, default=0, help_text='واحد پیش \u200cفرض (ریال)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(default=0, help_text='واحد پیش\u200cفرض (ریال)')),
                ('description', models.TextField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Budgeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minimum_target_amount', models.PositiveIntegerField(default=0, help_text='واحد پیش\u200cفرض (ریال)')),
                ('maximum_target_amount', models.PositiveIntegerField(default=0, help_text='واحد پیش\u200cفرض (ریال)')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_budget', to='api.category')),
            ],
            options={
                'ordering': ['-start_date'],
                'abstract': False,
                'unique_together': {('user', 'category', 'start_date', 'end_date')},
            },
        ),
    ]
