# Generated by Django 5.2.8 on 2025-11-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('income', 'درآمد'), ('expense', 'هزینه ضروری'), ('savings', 'پس\u200cانداز/سرمایه\u200cگذاری')], default='expense', max_length=20),
        ),
    ]
