# Generated by Django 5.2.7 on 2025-11-30 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_category_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['created_at', 'date']},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='record_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 9, 22, 42, 369809, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('income', 'درآمد'), ('expense', 'هزینه '), ('savings', 'پس\u200cانداز/سرمایه\u200cگذاری')], default='expense', max_length=20),
        ),
    ]
