# Generated by Django 5.2.7 on 2025-11-30 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.date(2025, 11, 30)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='record_date',
            field=models.DateTimeField(default=datetime.date(2025, 11, 30)),
        ),
    ]
